version: '3.4'

services:
  docker_sample_db:
    container_name: docker_sample_db
    image: "api-db:latest"
    ports:
      - 32456:80
    depends_on:
    - my_database
    - my_database2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mynetwork

  my_database:
    container_name: firstmysql2
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=testDB2
      - MYSQL_ROOT_PASSWORD=mysql123
    networks:
      - mynetwork

  my_database2:
    container_name: mysql
    image: "mysql:latest"
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=db1
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
